//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int gameID { get; set; }
        public string gameWinner { get; set; }
        public Nullable<System.DateTime> weeks { get; set; }
    
        public virtual Game_info Game_info { get; set; }
    }
}
